### ISSUE TITLE
menu is no longer themed

### ISSUE THREAD

**Issue by sean-e** [Zorziel/Dark-Gold#1]
on win 10, the main menu is no longer themed by Dark-Gold.

repro by pressing alt+f to show the File menu.
also repro by right-clicking on a web page to display the context menu.

i think this broke around firefox 90.

**Comment by Zorziel** [comment]
Confirmed.  

This broke somewhat with the UI change to Proton (~FF89), though was still following the system dark/light mode setting until 90.0 when it changed no matter what your system is set to.   There is no official documentation on setting the context menu in the manifest.json file (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme) but I did see some mentions on reddit that it is set from the inactive tab text where above a certain hex color value changes it to dark.  I am still working on testing getting dark menus without losing the grey text.  Hopefully we can find a fix that doesn't involve using custom userChrome.css tweaks.. or Mozilla fixes their UI..

Related: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1702427
https://bugzilla.mozilla.org/show_bug.cgi?id=1705501

Older bugs from the old UI with similar issues:
https://bugzilla.mozilla.org/show_bug.cgi?id=1553682
https://bugzilla.mozilla.org/show_bug.cgi?id=1681822

**Comment by Zorziel** [comment]
I found confirmation that it is the tab_background_text element that triggers the light/dark context menus: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1702427
https://github.com/mozilla/FirefoxColor/issues/979

> This is an (intentional?) feature of Firefox 89+ (Proton). Supposedly the "background tab text color" is chosen such that there is a good enough contrast with the background color. That means that if you choose a light/white "background tab text color", that the "background color" is expected to be somewhat dark, and that the dark theme is used for the menu.

Again, this is still not officially documented anywhere, but at least we have confirmation.  I'm going to play around with the colors to see if I can find the threshold that triggers it

**Comment by Zorziel** [comment]
The current value in the theme is `"tab_background_text": "rgb(125, 125, 125)"`

**Comment by Zorziel** [comment]
max rgb values are 255 and 255/2 = 127.5.  Trying `"tab_background_text": "rgb(130, 130, 130)"`

**Comment by Zorziel** [comment]
Updating the tab_background_text color to rgb(130, 130, 130) triggered the dark menus!  

The version with the fix, 3.9.1, was just approved by Mozilla and should be rolling out shortly... or you can force check for updates in your Add-Ons page to get it.  

![image](https://user-images.githubusercontent.com/46036567/130053651-adab0e93-744a-4689-b8b3-78f7938925cb.png)
![image](https://user-images.githubusercontent.com/46036567/130053731-8726a2c8-8201-4865-bebb-48fb653705e3.png)
